services:
  - type: web
    name: navus-enhanced
    env: python
    plan: starter
    buildCommand: "pip install -r requirements-production.txt"
    startCommand: "cd WebApp && python backend_production.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"